# note:
# change "workdir:" to "./workdir:" to bind locally and inspect the contents

version: '2'

volumes:
  workdir:

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - workdir:/usr/share/nginx/html

  unpacker:
    image: test
    ports:
      - 3000:3000
    volumes:
      - workdir:/app/workdir
    environment:
      SECRET_KEY: top_secret
      DEBUG: unpacker*
